rails_homepage: "https://www.railstutorial.org/"
rails_help: "https://www.railstutorial.org/help"
rails_book: "https://www.railstutorial.org/book"
learn_enough: "https://www.learnenough.com/"
rails_screencasts: "https://screencasts.railstutorial.org/"
